---
- hosts: all
  remote_user: ubuntu
  become: yes

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes # Roda apt-get update antes de fazer o apt-get i

    - name: Init nginx
      service:
        name: nginx
        state: started